import { CurrentUser, Employee } from './dashboard-types';

export const CURRENT_USER: CurrentUser = {
  id: 'me',
  name: 'Aditi Sharma',
  role: 'Product Design Lead',
  department: 'Design',
  email: 'aditi.sharma@company.com',
  phone: '+91 98765 43210',
  location: 'Guwahati, IN',
  joinDate: 'March 12, 2022',
};

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: '1',
    name: 'Rahul Verma',
    role: 'Frontend Engineer',
    department: 'Engineering',
    email: 'rahul.verma@company.com',
    phone: '+91 90000 11111',
    location: 'Bengaluru, IN',
    joinDate: 'Jan 4, 2021',
    presence: 'present',
  },
  {
    id: '2',
    name: 'Priya Nair',
    role: 'HR Manager',
    department: 'People Ops',
    email: 'priya.nair@company.com',
    phone: '+91 90000 22222',
    location: 'Mumbai, IN',
    joinDate: 'Jul 19, 2020',
    presence: 'on_leave',
  },
  {
    id: '3',
    name: 'Arjun Das',
    role: 'Backend Engineer',
    department: 'Engineering',
    email: 'arjun.das@company.com',
    phone: '+91 90000 33333',
    location: 'Guwahati, IN',
    joinDate: 'Nov 2, 2022',
    presence: 'absent',
  },
  {
    id: '4',
    name: 'Sneha Patil',
    role: 'Marketing Lead',
    department: 'Marketing',
    email: 'sneha.patil@company.com',
    phone: '+91 90000 44444',
    location: 'Pune, IN',
    joinDate: 'Feb 27, 2019',
    presence: 'present',
  },
  {
    id: '5',
    name: 'Vikram Singh',
    role: 'DevOps Engineer',
    department: 'Engineering',
    email: 'vikram.singh@company.com',
    phone: '+91 90000 55555',
    location: 'Delhi, IN',
    joinDate: 'Sep 9, 2023',
    presence: 'present',
  },
  {
    id: '6',
    name: 'Ananya Iyer',
    role: 'UX Researcher',
    department: 'Design',
    email: 'ananya.iyer@company.com',
    phone: '+91 90000 66666',
    location: 'Chennai, IN',
    joinDate: 'May 15, 2021',
    presence: 'on_leave',
  },
  {
    id: '7',
    name: 'Karan Mehta',
    role: 'Sales Executive',
    department: 'Sales',
    email: 'karan.mehta@company.com',
    phone: '+91 90000 77777',
    location: 'Ahmedabad, IN',
    joinDate: 'Aug 30, 2022',
    presence: 'absent',
  },
  {
    id: '8',
    name: 'Divya Reddy',
    role: 'QA Engineer',
    department: 'Engineering',
    email: 'divya.reddy@company.com',
    phone: '+91 90000 88888',
    location: 'Hyderabad, IN',
    joinDate: 'Oct 11, 2020',
    presence: 'present',
  },
  {
    id: '9',
    name: 'Manish Gupta',
    role: 'Finance Analyst',
    department: 'Finance',
    email: 'manish.gupta@company.com',
    phone: '+91 90000 99999',
    location: 'Kolkata, IN',
    joinDate: 'Dec 5, 2023',
    presence: 'present',
  },
];
